# Generated by Django 3.0.4 on 2020-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200310_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='site_set',
            field=models.TextField(default='-'),
        ),
    ]
