# Generated by Django 3.0.4 on 2020-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200403_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='site_set',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
