# Generated by Django 3.0.4 on 2020-04-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='catid',
            field=models.IntegerField(),
        ),
    ]
