# Generated by Django 3.0.4 on 2020-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='date',
            field=models.CharField(default='-', max_length=12),
        ),
    ]
